var test = {
	"About" : "查询赛程数据按日期查询",
	"DateScheduleList" : [ {
		"HomeCNAlias" : "魔术",
		"HomeCNName" : "奥兰多魔术",
		"HomeLargerLogo" : "Magic.png",
		"HomeTeamScore" : 105,
		"Attendance" : 15839,
		"HomeSmallLogo" : "Magic-1.png",
		"HomeENAlias" : "Orl",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 20,
		"MatchGTM8Time" : 1385596800000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "Phi",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385550038000,
		"TimeOfGameMinutes" : 6,
		"StadiumCNName" : "安利球馆",
		"VisitingENName" : "76ers",
		"HomeENName" : "Magic",
		"StadiumENName" : "Amway Center",
		"VisitingSmallLogo" : "76ers-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Jason Phillips",
		"VisitingLargerLogo" : "76ers.png",
		"ScheduleID" : 1348817,
		"VisitingTeamScore" : 94,
		"VisitingCNAlias" : "76人",
		"VisitingCNName" : "费城76人",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 19
	}, {
		"HomeCNAlias" : "山猫",
		"HomeCNName" : "夏洛特山猫",
		"HomeLargerLogo" : "Bobcats.png",
		"HomeTeamScore" : 74,
		"Attendance" : 15170,
		"HomeSmallLogo" : "Bobcats-1.png",
		"HomeENAlias" : "Cha",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 11,
		"MatchGTM8Time" : 1385596800000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "Ind",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385550038000,
		"TimeOfGameMinutes" : 29,
		"StadiumCNName" : "时代华纳有线球馆",
		"VisitingENName" : "Pacers",
		"HomeENName" : "Bobcats",
		"StadiumENName" : "Time Warner Cable Arena",
		"VisitingSmallLogo" : "Pacers-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Bill Kennedy",
		"VisitingLargerLogo" : "Pacers.png",
		"ScheduleID" : 1349825,
		"VisitingTeamScore" : 99,
		"VisitingCNAlias" : "步行者",
		"VisitingCNName" : "印地安那步行者",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 5312
	}, {
		"HomeCNAlias" : "凯尔特人",
		"HomeCNName" : "波士顿凯尔特人",
		"HomeLargerLogo" : "Celtics.png",
		"HomeTeamScore" : 93,
		"Attendance" : 17319,
		"HomeSmallLogo" : "Celtics-1.png",
		"HomeENAlias" : "Bos",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 29,
		"MatchGTM8Time" : 1385598600000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "Mem",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385551838000,
		"TimeOfGameMinutes" : 10,
		"StadiumCNName" : "TD北岸花园",
		"VisitingENName" : "Grizzlies",
		"HomeENName" : "Celtics",
		"StadiumENName" : "Fernando Buesa Arena",
		"VisitingSmallLogo" : "Grizzlies-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Nick Buchert",
		"VisitingLargerLogo" : "Grizzlies.png",
		"ScheduleID" : 1349119,
		"VisitingTeamScore" : 100,
		"VisitingCNAlias" : "灰熊",
		"VisitingCNName" : "孟菲斯灰熊",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 2
	}, {
		"HomeCNAlias" : "活塞",
		"HomeCNName" : "底特律活塞",
		"HomeLargerLogo" : "Pistons.png",
		"HomeTeamScore" : 79,
		"Attendance" : 14228,
		"HomeSmallLogo" : "Pistons-1.png",
		"HomeENAlias" : "Det",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 4,
		"MatchGTM8Time" : 1385598600000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "Chi",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385551838000,
		"TimeOfGameMinutes" : 9,
		"StadiumCNName" : "奥本山宫殿",
		"VisitingENName" : "Bulls",
		"HomeENName" : "Pistons",
		"StadiumENName" : "The Palace of Auburn Hills",
		"VisitingSmallLogo" : "Bulls-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Scott Foster",
		"VisitingLargerLogo" : "Bulls.png",
		"ScheduleID" : 1349682,
		"VisitingTeamScore" : 99,
		"VisitingCNAlias" : "公牛",
		"VisitingCNName" : "芝加哥公牛",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 8
	}, {
		"HomeCNAlias" : "篮网",
		"HomeCNName" : "布鲁克林篮网队",
		"HomeLargerLogo" : "BrooklynNets.png",
		"HomeTeamScore" : 94,
		"Attendance" : 17732,
		"HomeSmallLogo" : "sBrooklynNets.png",
		"HomeENAlias" : "Bkn",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 13,
		"MatchGTM8Time" : 1385598600000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "LAL",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385551838000,
		"TimeOfGameMinutes" : 20,
		"StadiumCNName" : "巴克莱中心",
		"VisitingENName" : "Lakers",
		"HomeENName" : "Nets",
		"StadiumENName" : "Barclays Center",
		"VisitingSmallLogo" : "Lakers-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Mike Callahan",
		"VisitingLargerLogo" : "Lakers.png",
		"ScheduleID" : 1348929,
		"VisitingTeamScore" : 99,
		"VisitingCNAlias" : "湖人",
		"VisitingCNName" : "洛杉矶湖人",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 17
	}, {
		"HomeCNAlias" : "骑士",
		"HomeCNName" : "克里夫兰骑士",
		"HomeLargerLogo" : "Cavaliers.png",
		"HomeTeamScore" : 84,
		"Attendance" : 20562,
		"HomeSmallLogo" : "Cavaliers-1.png",
		"HomeENAlias" : "Cle",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 14,
		"MatchGTM8Time" : 1385598600000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "Mia",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385551838000,
		"TimeOfGameMinutes" : 21,
		"StadiumCNName" : "速贷",
		"VisitingENName" : "Heat",
		"HomeENName" : "Cavaliers",
		"StadiumENName" : "CSKA Universal Sports Hall",
		"VisitingSmallLogo" : "Heat-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Matt Boland",
		"VisitingLargerLogo" : "Heat.png",
		"ScheduleID" : 1349387,
		"VisitingTeamScore" : 95,
		"VisitingCNAlias" : "热火",
		"VisitingCNName" : "迈阿密热",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 5
	}, {
		"HomeCNAlias" : "火箭",
		"HomeCNName" : "休斯敦火箭",
		"HomeLargerLogo" : "Rockets.png",
		"HomeTeamScore" : 113,
		"Attendance" : 18051,
		"HomeSmallLogo" : "Rockets-1.png",
		"HomeENAlias" : "Hou",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 1,
		"MatchGTM8Time" : 1385600400000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "Atl",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385550038000,
		"TimeOfGameMinutes" : 3,
		"StadiumCNName" : "丰田中心",
		"VisitingENName" : "Hawks",
		"HomeENName" : "Rockets",
		"StadiumENName" : "Fenerbahce Ulker Arena",
		"VisitingSmallLogo" : "Hawks-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Curtis Blair",
		"VisitingLargerLogo" : "Hawks.png",
		"ScheduleID" : 1349205,
		"VisitingTeamScore" : 84,
		"VisitingCNAlias" : "老鹰",
		"VisitingCNName" : "亚特兰大老鹰",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 10
	}, {
		"HomeCNAlias" : "森林狼",
		"HomeCNName" : "明尼苏达森林狼",
		"HomeLargerLogo" : "Timberwolves.png",
		"HomeTeamScore" : 110,
		"Attendance" : 14244,
		"HomeSmallLogo" : "Timberwolves-1.png",
		"HomeENAlias" : "Min",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 7,
		"MatchGTM8Time" : 1385600400000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "Den",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385550038000,
		"TimeOfGameMinutes" : 21,
		"StadiumCNName" : "标靶中心",
		"VisitingENName" : "Nuggets",
		"HomeENName" : "Timberwolves",
		"StadiumENName" : "KeyArena",
		"VisitingSmallLogo" : "Nuggets-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Marc Davis",
		"VisitingLargerLogo" : "Nuggets.png",
		"ScheduleID" : 1348920,
		"VisitingTeamScore" : 117,
		"VisitingCNAlias" : "掘金",
		"VisitingCNName" : "丹佛掘金",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 16
	}, {
		"HomeCNAlias" : "雄鹿",
		"HomeCNName" : "密尔沃基雄鹿",
		"HomeLargerLogo" : "Bucks.png",
		"HomeTeamScore" : 92,
		"Attendance" : 11584,
		"HomeSmallLogo" : "Bucks-1.png",
		"HomeENAlias" : "Mil",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 27,
		"MatchGTM8Time" : 1385600400000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 5,
		"VisitingENAlias" : "Was",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385550038000,
		"TimeOfGameMinutes" : 27,
		"StadiumCNName" : "BMO哈里斯中心球馆",
		"VisitingENName" : "Wizards",
		"HomeENName" : "Bucks",
		"StadiumENName" : "BMO Harris Bradley Center",
		"VisitingSmallLogo" : "Wizards-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Ken Mauer",
		"VisitingLargerLogo" : "Wizards.png",
		"ScheduleID" : 1349369,
		"VisitingTeamScore" : 100,
		"VisitingCNAlias" : "奇才",
		"VisitingCNName" : "华盛顿奇才",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 15
	}, {
		"HomeCNAlias" : "雷霆",
		"HomeCNName" : "俄克拉荷马雷霆",
		"HomeLargerLogo" : "Thunder.png",
		"HomeTeamScore" : 94,
		"Attendance" : 18203,
		"HomeSmallLogo" : "sThunder.png",
		"HomeENAlias" : "OKC",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 24,
		"MatchGTM8Time" : 1385600400000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "SA",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385550038000,
		"TimeOfGameMinutes" : 2,
		"StadiumCNName" : "切萨皮克能源球馆",
		"VisitingENName" : "Spurs",
		"HomeENName" : "Thunder",
		"StadiumENName" : "Chesapeake Energy Arena",
		"VisitingSmallLogo" : "Spurs-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Monty McCutchen",
		"VisitingLargerLogo" : "Spurs.png",
		"ScheduleID" : 1349301,
		"VisitingTeamScore" : 88,
		"VisitingCNAlias" : "马刺",
		"VisitingCNName" : "圣安东尼奥马刺",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 25
	}, {
		"HomeCNAlias" : "小牛",
		"HomeCNName" : "达拉斯小牛",
		"HomeLargerLogo" : "Mavericks.png",
		"HomeTeamScore" : 103,
		"Attendance" : 20211,
		"HomeSmallLogo" : "Mavericks-1.png",
		"HomeENAlias" : "Dal",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 9,
		"MatchGTM8Time" : 1385602200000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "GS",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385551838000,
		"TimeOfGameMinutes" : 14,
		"StadiumCNName" : "美国航空中心球场",
		"VisitingENName" : "Warriors",
		"HomeENName" : "Mavericks",
		"StadiumENName" : "American Airlines Center",
		"VisitingSmallLogo" : "Warriors-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Ron Garretson",
		"VisitingLargerLogo" : "Warriors.png",
		"ScheduleID" : 1348851,
		"VisitingTeamScore" : 99,
		"VisitingCNAlias" : "勇士",
		"VisitingCNName" : "金州勇士",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 6
	}, {
		"HomeCNAlias" : "太阳",
		"HomeCNName" : "菲尼克斯太阳",
		"HomeLargerLogo" : "Suns.png",
		"HomeTeamScore" : 120,
		"Attendance" : 12731,
		"HomeSmallLogo" : "Suns-1.png",
		"HomeENAlias" : "Pho",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 22,
		"MatchGTM8Time" : 1385604000000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "Por",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385550038000,
		"TimeOfGameMinutes" : 9,
		"StadiumCNName" : "美航中心",
		"VisitingENName" : "Trail Blazers",
		"HomeENName" : "Suns",
		"StadiumENName" : "Palau Blaugrana",
		"VisitingSmallLogo" : "TrailBlazers-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Tony Brothers",
		"VisitingLargerLogo" : "TrailBlazers.png",
		"ScheduleID" : 1348753,
		"VisitingTeamScore" : 106,
		"VisitingCNAlias" : "开拓者",
		"VisitingCNName" : "波特兰开拓者",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 21
	}, {
		"HomeCNAlias" : "快船",
		"HomeCNName" : "洛杉矶快船",
		"HomeLargerLogo" : "Clippers.png",
		"HomeTeamScore" : 93,
		"Attendance" : 19270,
		"HomeSmallLogo" : "Clippers-1.png",
		"HomeENAlias" : "LAC",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 18,
		"MatchGTM8Time" : 1385609400000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "NY",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385551838000,
		"TimeOfGameMinutes" : 12,
		"StadiumCNName" : "斯台普斯",
		"VisitingENName" : "Knicks",
		"HomeENName" : "Clippers",
		"StadiumENName" : "Palasport Mens Sana",
		"VisitingSmallLogo" : "Knicks-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Joe Crawford",
		"VisitingLargerLogo" : "Knicks.png",
		"ScheduleID" : 1349336,
		"VisitingTeamScore" : 80,
		"VisitingCNAlias" : "尼克斯",
		"VisitingCNName" : "纽约尼克斯",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 12
	}, {
		"HomeCNAlias" : "快船",
		"HomeCNName" : "洛杉矶快船",
		"HomeLargerLogo" : "Clippers.png",
		"HomeTeamScore" : 93,
		"Attendance" : 19270,
		"HomeSmallLogo" : "Clippers-1.png",
		"HomeENAlias" : "LAC",
		"Seconds" : 0.0,
		"StatusCNName" : "已完赛",
		"VisitingTeamID" : 18,
		"MatchGTM8Time" : 1385609400000,
		"StatusENName" : "Final",
		"MatchTypeENName" : "Regular Season",
		"TotalQuarters" : 4,
		"VisitingENAlias" : "NY",
		"TimeOfGameHours" : 2,
		"MatchLocalTime" : 1385551838000,
		"TimeOfGameMinutes" : 12,
		"StadiumCNName" : "斯台普斯",
		"VisitingENName" : "Knicks",
		"HomeENName" : "Clippers",
		"StadiumENName" : "Palasport Mens Sana",
		"VisitingSmallLogo" : "Knicks-1.png",
		"RefereeCNName" : null,
		"RefereeENName" : "Dan Crawford",
		"VisitingLargerLogo" : "Knicks.png",
		"ScheduleID" : 1349336,
		"VisitingTeamScore" : 80,
		"VisitingCNAlias" : "尼克斯",
		"VisitingCNName" : "纽约尼克斯",
		"MatchTypeCNName" : "常规赛",
		"Minutes" : 0,
		"HomeTeamID" : 12
	} ]
}
